# Generated by Django 5.2.1 on 2025-05-28 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('AP', 'Andhra Pradesh'), ('KA', 'Karnataka')], max_length=2)),
                ('location', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('urgent', 'Urgent (2 days left)'), ('month1', '1 Month Left'), ('month2', '2 Months Left'), ('month3', '3 Months Left')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
